### ISSUE TITLE
[request] Integration WT with WB-weather

### ISSUE THREAD

**Issue by mohace** [delightedCrow/WallberryTheme#14]
Hi. Could You integrate these two modules in only one and after that make that, according with responses from weather server for the current weather, WT takes a random pic from unsplash collections with the same label (You could create its, or me, if you need help). For example, sunny or any other label (cloudy, windy), in the same way that WB-W takes the icons.
In that way, the wallpaper would show pics according weather, if the code permits to change collection dynamically. It would be a new diferent module.
Thanks in advance.

**Comment by delightedCrow** [comment]
I've always liked the idea of eventually having the Wallberry theme be able to change dynamically in response to other modules (especially weather), but I doubt I'll have the time to implement it any time soon. 
Same goes for implementing a whole different theme (although since so many people like the option of using the theme with different weather modules I rather like the loose integration approach). You're of course welcome to create a new theme from WallberryTheme and WB-Weather if you like :)
