### ISSUE TITLE
Working with other modules

### ISSUE THREAD

**Issue by Kevsw99** [delightedCrow/WallberryTheme#2]
Hi, this is more of a question rather than an issue, so does this theme work with other modules such as MMM Remote Control and such? Like every other modules i have ever added into the Config.JS.

**Comment by delightedCrow** [comment]
I haven't done much testing with other modules so YMMV, but it was intended to play nice with others so in theory it should work fine with other modules :)
I'm not sure about MMM Remote Control specifically since I haven't gotten around to installing it yet, but it's on my list so if there are compatibility issues I'll probably look into fixing those eventually. Feel free to open an issue/feature request if you see it breaking other modules or want better integration.
