### ISSUE TITLE
API doesn't seem to get authenticated

### ISSUE THREAD

**Issue by roccodicarlo** [delightedCrow/WallberryTheme#20]
I created an account, created an APP and got an access key on unsplash.com.

However, whem the module executes, I get an unauthrized error.  My app is a demo app (not production on unsplah).  Also, under my profile on unsplash, I don't see anyway to add the APP I created in the development portal to the profile to allow access to my account collections.  Since I am only using public pictures, I don't think it should matter.  Do I have to wait for them to approve it first.

**Comment by delightedCrow** [comment]
The demo app should be fine - you don't need to have it approved to use it for the WallberryTheme.

The first thing I would check is to make sure you're using your Unsplash **Access Key** (not the Secret Key, Unsplash will give you two) when you set the `unsplashAccessKey` setting in your Magic Mirror config.

In order to choose which collections you want to show up you'll add the IDs for the collections you want to see to the WallberryTheme config settings (see https://github.com/delightedCrow/WallberryTheme#configuration-options), it won't choose the collections based on which ones you have in your profile.

**Comment by roccodicarlo** [comment]
I tried to execute the URL manually on my browser and it worked so I know that the Key and collections ID are correct.  Perhaps it is orientation attribute that is causing it.  I did not test it manually with orientation attribute

**Comment by delightedCrow** [comment]
could you post your config.js (with API keys redacted)?

**Comment by roccodicarlo** [comment]
{
    module: "WallberryTheme",
    position: "fullscreen_below", // Required Position
    config: {
      unsplashAccessKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", // REQUIRED
      collections: "9966805", // optional - leave empty for a random photo
      updateInterval:600000
    /*  orientation: "portrait",
      backgroundOpacity: .5,
      brightImageOpacity: .5 */
    }
  },

I have commented out the weather and clock

**Comment by delightedCrow** [comment]
awesome, thanks. Also, what errors are you getting in the developer tools console?

**Comment by roccodicarlo** [comment]
I am running a CLI server version of RPI on an RPI zero, and so I really can't access the web page using a gui editor...Is there a log file that I can check?

**Comment by delightedCrow** [comment]
you should be able to use `npm start dev` to start MM with electron's dev tools enabled

**Comment by roccodicarlo** [comment]
I get an error with electron when I try to run in dev mode...it is asking for me to re-install electron..it will take me some time

**Comment by roccodicarlo** [comment]
I updated electron and now everything works...thanks for your help

**Comment by delightedCrow** [comment]
welcome, glad you got it working :)
