### ISSUE TITLE
Issues with Options parameters

### ISSUE THREAD

**Issue by melin360** [delightedCrow/WallberryTheme#3]
Hello,
Everytime I'm trying to set the optional parameters updateInterval and resizeForScreen fails (with or withou "" on the value). 

Error: WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
This is an example of my config

modules: [
		
{
		module: "WallberryTheme",
		position: "fullscreen_below", // Required Position
		
		config: {
			unsplashAccessKey: "XXXX", // REQUIRED
			collections: "2589108,1424240,181,332024"
			updateInterval: "1200000"
			resizeForScreen: "true"
			
		}
	},
	// WB-clock adds local time (Optional Module)
	{
		module: "WallberryTheme/WB-clock",
		position: "top_bar", // highly suggest using top_bar position
		config: {
			localCityName: "Dublin", // optional
			otherCities: [
				{name: "Madrid", timezone: "Europe/Madrid"}, // optional
				{name: "Anchorage", timezone: "US/Alaska"} //optional
			]
		}
	},
	// WB-weather adds weather via DarkSky API (Optional Module)
	{
		module: "WallberryTheme/WB-weather",
		position: "bottom_bar",  // Highly suggested location
		config: {
			// See "Configuration options" for more information.
			darkSkyApiKey: "XXXXX",
			latitude:   3.473,
			longitude: -6.2418
		}
	}

	]

**Comment by delightedCrow** [comment]
hi! It looks like you're getting syntax errors because you're missing commas at the end of each parameter the first config block. Also, `updateInterval` should be a number (not a string), and `resizeForScreen` should be a boolean (the default is already set to true though so you don't need to set it again if you want the pictures to resize).

For example, you'll want something like this for that first config block:
```
config: {
		unsplashAccessKey: "XXXX",
		collections: "2589108,1424240,181,332024",
		updateInterval: 1200000
	}
```
