### ISSUE TITLE
White space at right and botom of screen 

### ISSUE THREAD

**Issue by djloot** [delightedCrow/WallberryTheme#34]
I'm using your module in portrait mode with two different monitors.  One is a 4k monitor, the other a 1920x1080 monitor.
Both are displaying the same white space at the right side and bottom of screen. 

When I use the wallpaper module, I do not have this issue.  
I am also using the fast-css module for formatting, so maybe the white color is coming from that, but I don't have the same issue with the wallpaper module

**Comment by delightedCrow** [comment]
I'm not seeing this effect on my installs so I think you're probably right about this being caused by a conflict with another module. I'm not familiar with the fast-css module, but if you're using it to change the css/formatting of your mirror that does seem like the thing likeliest to cause the bug you describe. 

It's hard to give advice without knowing what your config.js looks like (and what other modules you have installed), but you could try starting with only the WallberryTheme module enabled, and then enable your other modules one-by-one to see if you can isolate which modules are introducing the conflict.
