### ISSUE TITLE
Missing css reference

### ISSUE THREAD

**Issue by vincep5** [delightedCrow/WallberryTheme#9]
While looking at the MagicMirror via the browser, it is showing this error in the Dev toolbar

![image](https://user-images.githubusercontent.com/26965876/52645147-cf112680-2ea5-11e9-99a1-932bc9ad161f.png)

the font-awesome5.css ref is on line 31 of WallberryTheme.js

**Comment by delightedCrow** [comment]
Ooops, FontAwesome 5 is only included in [MagicMirror v2.6.0 ](https://forum.magicmirror.builders/topic/9376/v2-6-0), so you'll get this error if you're running an earlier version of MM (or if you haven't run npm install since upgrading to 2.6.0). 
I probably should have done a MM version check before trying to include that file just in case (or just stuck to font awesome 4 for the error message icons, lol).

**Comment by vincep5** [comment]
I'm running latest MM.  I think the issue is where the code is trying to pull in that CSS file.  It's looking at your WallberryTheme folder.   I'm not sure, havent looked, if its somewhere else in another MM folder.  Nothing is breaking, but you can adjust it at your next release.  Thanks for the reply

**Comment by delightedCrow** [comment]
no worries - MM should automatically fall back to its vendor folder for the font awesome 5 files if it doesn't find them in the local module folder, so if they're also missing from the vendor folder then running `npm install` in the MagicMirror directory should fix that for you.

**Comment by vincep5** [comment]
ah!  Ok.  thanks for the help, I didnt know that.  I'm actually on the dev branch of MM, so maybe they have changed something there versus the latest master branch.

**Comment by delightedCrow** [comment]
ah, that's probably the case :)
